[workspace]
default-members = [
    "postgresql_archive",
    "postgresql_commands",
    "postgresql_embedded",
    "postgresql_extensions",
]
members = [
    "examples/*",
    "postgresql_archive",
    "postgresql_commands",
    "postgresql_embedded",
    "postgresql_extensions",
]
resolver = "2"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["database"]
edition = "2021"
keywords = ["postgresql", "postgres", "embedded", "database", "server"]
license = "(Apache-2.0 OR MIT) AND PostgreSQL"
repository = "https://github.com/theseus-rs/postgresql-embedded"
version = "0.17.0"

[workspace.dependencies]
anyhow = "1.0.89"
async-trait = "0.1.83"
axum = "0.7.7"
criterion = "0.5.1"
diesel = "2.2.4"
diesel_migrations = "2.2.0"
flate2 = "1.0.34"
futures-util = "0.3.30"
hex = "0.4.3"
home = "0.5.9"
http = "1.1.0"
human_bytes = { version = "0.4.3", default-features = false }
indicatif = "0.17.8"
indoc = "2.0.5"
liblzma = "0.3.4"
md-5 = "0.10.6"
num-format = "0.4.4"
pgvector = "0.4.0"
postgres = "0.19.9"
quick-xml = "0.36.2"
r2d2_postgres = "0.18.1"
rand = "0.8.5"
regex = "1.11.0"
reqwest = { version = "0.12.7", default-features = false }
reqwest-middleware = "0.3.3"
reqwest-retry = "0.6.1"
reqwest-tracing = "0.5.3"
semver = "1.0.23"
serde = "1.0.210"
serde_json = "1.0.128"
sha1 = "0.10.6"
sha2 = "0.10.8"
sqlx = { version = "0.8.2", default-features = false, features = ["postgres"] }
tar = "0.4.42"
target-triple = "0.1.3"
test-log = "0.2.16"
tempfile = "3.13.0"
thiserror = "1.0.64"
tokio = "1.40.0"
tracing = "0.1.40"
tracing-indicatif = "0.3.6"
tracing-subscriber = "0.3.18"
url = "2.5.2"
zip = "2.2.0"

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"
