[package]
edition.workspace = true
name = "postgres_embedded"
publish = false
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
postgres = { workspace = true }
postgresql_embedded = { path = "../../postgresql_embedded", features = ["blocking"] }
